controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      ros__parameters:
        publish_rate: 10  # Hz

    hardware:
      type: arctos_hardware_interface/ArctosHardwareInterface  # Use your custom hardware interface
      ros__parameters:
        joints:
          - joint_1
          - joint_2
          - joint_3
          - joint_4
          - joint_5
          - joint_6
          
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      ros__parameters:
        joint_names:
          - joint_1
          - joint_2
          - joint_3
          - joint_4
          - joint_5
          - joint_6
        # You can add other parameters like gains, limits, etc. if needed
